### ISSUE TITLE
Final Capstone Project(Concert Booking Application)

### ISSUE THREAD

**Issue by Stephen-Adom** [Stephen-Adom/concert-rails-back-end#17]
1. [Concert Project](https://github.com/users/Stephen-Adom/projects/7)
2. There are 4 people in this group (@Stephen-Adom @AmineDerbal @AmanWorku @codedit334 )
![Screenshot 2023-07-13 095748](https://github.com/Stephen-Adom/concert-rails-back-end/assets/42853016/fe145e92-b944-41b8-bc9f-8662c63e359c)

**Comment by Meltrust** [comment]
Hi @Stephen-Adom,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have descriptions, have been assigned, and the pointings meet the project requirement ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
